language: ruby
script: bundle exec rspec spec
rvm:
  - jruby-head
gemfile:
  - gemfiles/mongoid3.gemfile
  - gemfiles/active_record.gemfile
services:
  - mongodb
  - rabbitmq
  - redis-server
before_script:
  - psql -c 'create database promiscuous;' -U postgres
