language: ruby
bundler_args: --without development
script: bundle exec rspec spec
env: TIMEOUT=10
rvm:
  - ruby-2.0.0
  - ruby-2.1.0
  - ruby-2.2.0
gemfile:
  - gemfiles/mongoid31.gemfile
  - gemfiles/mongoid40.gemfile
  - gemfiles/active_record32.gemfile
  - gemfiles/active_record40.gemfile
  - gemfiles/active_record40_mysql.gemfile
services:
  - mongodb
  - rabbitmq
  - redis-server
